# **Introduction to Machine Learning**

## Difference in Data Science and Data Analytics?
- Data Analytics answeres What and How?
- Data Science answers what may happen?
> it's important to know data analytics to do data science.

# Update this section from cuckoo's laptop (first and second class)
## What does Data Scientist do day to day?
- **Data Cleaning**
- **Data Preprocessing** : formating data favourable for analysing further
- **EDA** : Exploratory data analysis  (impacts of variables and understanding data)
- **Feature engineering** : clreating new column scalling data
- **Model Building**
- **Model Evaluation** : checks how good the predictions are?
- **Model Deployment**
- **Maintanance**

### Concept of scaling

convert data to a range 

In *standard scaler* mean is zero and std-dev is 1

## Mainly there are 3 Types of Machine Learning :

#### Supervised
- Data / Input / Feature and Label / Output / Target
- Data can have n-number of columns but Label will have only one column
> Old car price prediction
- Feature : age,maker , model, seat, abs, features
- Target : Price

> Loan approver
- Feature : Education, Age, Credit, Account, Reside, Area
- Target : Approve/Disapprove

> Basically we teach the machine by providing example i.e, Feature and Target


#### Unsupervised
- Only Data / Input / Feature is provided and we find pattern by simillarity measures.
- We give input and machine tells us what the pattern is.

> we are giving data of customers of D-Mart to machine and it returns categories of customers

> A child segregating chocolates, chips and biscuits on it's own.


#### Reinforcment

- Data and Label both are given to the machine and it makes changes according to the feedback, judging on it's own output or feed back from user

# Data Science SDLC

-  EDA
    - Pandas
    - Numpy
    - Matplotlib / Seaborn
    - Scipy

- Feature engineering
    - Pandas
    - Numpy 
    - sklearn
    - imblearn
    - statmodes

- Model Builidng / Model Evaluation
    - sklearn

# EDA

In [1]:
# importing PreRequisites
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

import warnings
warnings.filterwarnings("ignore")

In [4]:
# importing data
data = pd.read_csv("Data/Diabetes Dataset.csv")
df = data.copy()
df

,Diabetes_012,HighBP,HighChol,CholCheck,BMI,Smoker,Stroke,HeartDiseaseorAttack,PhysActivity,Fruits,...,AnyHealthcare,NoDocbcCost,GenHlth,MentHlth,PhysHlth,DiffWalk,Gender,Age,Education,Income
0,0,1,1,1,40,1,0,0,0,0,...,1,0,5,18,15,1,0,9,4,3
1,0,0,0,0,25,1,0,0,1,0,...,0,1,3,0,0,0,0,7,6,1
2,0,1,1,1,28,0,0,0,0,1,...,1,1,5,30,30,1,0,9,4,8
3,0,1,0,1,27,0,0,0,1,1,...,1,0,2,0,0,0,0,11,3,6
4,0,1,1,1,24,0,0,0,1,1,...,1,0,2,3,0,0,0,11,5,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
253675,0,1,1,1,45,0,0,0,0,1,...,1,0,3,0,5,0,1,5,6,7
253676,2,1,1,1,18,0,0,0,0,0,...,1,0,4,0,0,1,0,11,2,4
253677,0,0,0,1,28,0,0,0,1,1,...,1,0,1,0,0,0,0,2,5,2
253678,0,1,0,1,23,0,0,0,0,1,...,1,0,3,0,0,0,1,7,5,1
253679,2,1,1,1,25,0,0,1,1,1,...,1,0,2,0,0,0,0,9,6,2